language: python
python:
  - "2.7"
  - "3.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install qq swig libgphoto2-dev

script:
  - python setup.py build_swig
  - python setup.py build
